name: go-build-and-test-amd64
on:
    push:
    pull_request:
    schedule:
      - cron: "0 8 * * 0" # every sunday

permissions:
  contents: read

jobs:
  ci:
    uses: Mellanox/cloud-orchestration-reusable-workflows/.github/workflows/go-ci-reusable.yml@main
    with:
      runner: ubuntu-22.04
      lint-command: ""
      test-command: |
        make test
        make test-coverage
      coverage-file: ipoib-cni.cover
