name: "push images on release"

on:
  push:
    tags:
      - v*
jobs:
  build-and-push-ipoib-cni:
    runs-on: ubuntu-22.04
    name: image push
    steps:
      - name: Set repository as lower-case output variable
        id: repo_name
        run: echo ::set-output name=repository::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')

      - name: check out the repo
        uses: actions/checkout@v3

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: login to Docker
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ steps.repo_name.outputs.repository }}
          tags: |
            type=ref,event=tag

      - name: build and push ipoib-cni
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64,linux/ppc64le
          tags: |
            ${{ steps.docker_meta.outputs.tags }}
          file: ./Dockerfile
